In [1]:
import numpy as np
x = [12,11,10,19]
data = np.array(x)
print(data)

[12 11 10 19]


In [2]:
x = [.06,.05,.03,.07]
data = np.array(x)
print(data)

[0.06 0.05 0.03 0.07]


In [3]:
x = ([1,2,3],[2,3,4])
data = np.array(x)
print(data)

[[1 2 3]
 [2 3 4]]


Updates about the image to numpy assignments

you need to download 20 photos and save in the photos folder

use the following codes to scan the folder (change folder name from '.' to photos

 Import the os module, for the os.walk function
 
import os

Set the directory you want to start from

rootDir = '.'
for dirName, subdirList, fileList in os.walk(rootDir):
print('Found directory: %s' % dirName)
for fname in fileList:
print('\t%s' % fname)
print('Found directory: %s' % dirName)
to for fname in fileList:e name (with input) as input and load it and resize it to 200, 200, 3)  

and return a numpy array. you need an image resize library like PIL

4) store this numpy array of the image into the main array (created earlier in the code with 20, 200, 200, 3 dimensions 

Note: you can find some partial code in this group

In [9]:
x = [2.099999999,3,4,5,6]
y = [8,9,0,5,3]
xx = np.array(x,dtype = np.int32 )
yy = np.array(y,dtype = np.float64 )
print(xx)


[2 3 4 5 6]


In [16]:
x = np.array([1,2,3,4,5,6])
y = np.array([4,5,6,7,9,0])
data = x*y
print(data)

[ 4 10 18 28 45  0]


In [7]:
import numpy as np
x = np.arange(10)
print(x[:])

[0 1 2 3 4 5 6 7 8 9]


In [25]:
arr1 = [(0,1),(1,3),(2,4)]
arr2 = [(4,3),(5,2),(6,1)]
arr3 = [(7,9),(8,2),(9,0)]
print(int(arr1[0][0])*int(arr2[0][1]))

0


In [28]:
y = ['Melissa']
x = ['Bob','Dwayne','Melissa','Tim','Sila']
a = np.array(x)
b = np.array(y)
a==b



array([False, False,  True, False, False])

In [37]:
np.arange(0:5:1)


SyntaxError: invalid syntax (<ipython-input-37-acc65d249e99>, line 1)

In [39]:
points = np.arange(-5, 5, 0.01)
xs, ys = np.meshgrid(points, points)
ys


array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ...,
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [1]:
import numpy as np
array1 = np.empty((12,5))
for x in range(12):
    array1(x) = x 
    
print(array1)

SyntaxError: can't assign to function call (<ipython-input-1-244c9b3054a9>, line 4)

In [12]:
import numpy as np
x = np.arange(10)
print(x)
data = [
    x[0:2],
    x[0:3],
    x[4:8]
]
data

[0 1 2 3 4 5 6 7 8 9]


[array([0, 1]), array([0, 1, 2]), array([4, 5, 6, 7])]

In [13]:
names = np.array(['bob','smith','sammy','bill','tom','marsh','ben'])
names[0:4]

array(['bob', 'smith', 'sammy', 'bill'], dtype='<U5')

In [18]:
import numpy as np
names = np.array(['bob','smith','sammy','bill','tom','marsh','ben'])
data = np.random.randn(6,4)
data

array([[ 0.94519236, -0.57484115,  0.07685547, -1.68344495],
       [ 2.01380252, -1.47841611, -1.02231076, -0.33277568],
       [-0.92829476, -1.43087183,  0.53441088,  0.49382484],
       [-0.09405487,  0.70580991,  0.39952646, -0.37438057],
       [-1.22428068,  0.90886948, -0.18151426,  0.16362792],
       [ 1.73217061, -2.04011572,  1.44534813, -0.31194265]])

In [21]:
    array = np.array([ array[1,2,3],array[2,3,4],array[4,7,8]
                       array[0,1,0],array[9,7,8],array[9,3,4]
                       array[2,3,5],array[5,6,7],array[7,8,9] ])
    array1 = [array[0][2], array[0][1],
              array[1][1], array[1][2] ]
    array1

SyntaxError: invalid syntax (<ipython-input-21-ddb6c742b62f>, line 2)

In [31]:
import numpy as np
array1 = np.arange(60).reshape(6,5,2)
array1

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]],

       [[50, 51],
        [52, 53],
        [54, 55],
        [56, 57],
        [58, 59]]])

In [29]:
array1.transpose()

array([[ 0, 10, 20, 30, 40, 50],
       [ 1, 11, 21, 31, 41, 51],
       [ 2, 12, 22, 32, 42, 52],
       [ 3, 13, 23, 33, 43, 53],
       [ 4, 14, 24, 34, 44, 54],
       [ 5, 15, 25, 35, 45, 55],
       [ 6, 16, 26, 36, 46, 56],
       [ 7, 17, 27, 37, 47, 57],
       [ 8, 18, 28, 38, 48, 58],
       [ 9, 19, 29, 39, 49, 59]])